export default [
  {name: 'AccorHotels', hotels: ['Mercure', 'Novotel', 'Sofitel', 'Fairmont']},
  {name: 'AmericInn', hotels: ['AmericInn']},
  {name: 'Best Western Hotels', hotels: ['Best Western', 'Best Western Plus']},
  {name: 'Carlson Rezidor Hotel Group', hotels: ['Park Inn', 'Country Inns & Suites', 'Radisson', 'Park Plaza']},
  {name: 'Choice Hotels', hotels: ['Econo Lodge', 'Rodeway Inn', 'Suburban Extended Stay Hotel', 'Mainstay Suites', 'Quality Inn', 'Comfort Inn', 'Sleep Inn', 'Comfort Suites', 'Clarion Inn', 'Cambria Suites', 'Clarion Hotel']},
  {name: 'Drury Hotels', hotels: ['Pear Tree Inn', 'Drury Inn and Suites']},
  {name: 'Extended Stay America Inc', hotels: ['Extended Stay America']},
  {name: 'Four Seasons Hotels and Resorts', hotels: ['Four Seasons Hotels']},
  {name: 'Hilton Worldwide', hotels: ['Hampton by Hilton', 'Hilton Garden Inn', 'Homewood Suites by Hilton', 'Home2 Suites', 'Embassy Suites by Hilton', 'Hilton', 'DoubleTree', 'Waldorf Astoria']},
  {name: 'Hyatt Hotels Corporation', hotels: ['Hyatt Place', 'Hyatt Regency', 'Hyatt Hotels', 'Grand Hyatt', 'Andaz (hotel)']},
  {name: 'InterContinental Hotels Group (IHG)', hotels: ['Holiday Inn Express', 'Candlewood Suites', 'Holiday Inn', 'Hotel Indigo', 'Staybridge Suites', 'Holiday Inn Select', 'Crowne Plaza', 'InterContinental']},
  {name: 'La Quinta Inns & Suites', hotels: ['La Quinta Inns & Suites']},
  {name: 'Marriott International', hotels: ['TownePlace Suites', 'AC Hotels', 'Fairfield Inn by Marriott', 'Courtyard by Marriott', 'SpringHill Suites', 'Residence Inn by Marriott', 'Four Points by Sheraton', 'Aloft Hotels', 'Renaissance Hotels', 'Marriott', 'Autograph Collection', 'Gaylord Hotels', 'W Hotels', 'Design Hotels', 'Westin Hotels & Resorts', 'Le Méridien', 'Sheraton', 'Tribute Portfolio', 'Ritz-Carlton', 'Bulgari Hotels', 'JW Marriott Hotels', 'St. Regis']},
  {name: 'Motel 6', hotels: ['Motel 6', 'Studio 6']},
  {name: 'Omni Hotels & Resorts', hotels: ['Omni Hotels & Resorts']},
  {name: 'Shilo Inns', hotels: ['Shilo Inns']},
  {name: 'Red Lion', hotels: ['Americas Best Value Inn', 'Canadas Best Value Inn', 'Country Hearth Inn & Suites', 'Signature Inn', 'Settle Inn', 'Guest House', 'Lexington', 'Jameson Inn', 'Red Lion Inn & Suites']},
  {name: 'Wyndham Worldwide', hotels: ['Days Inn', 'Super 8', 'Travelodge', 'Knights Inn', 'Microtel Inn & Suites by Wyndham', 'Howard Johnson\'s', 'Baymont Inn & Suites', 'Ramada Plaza', 'Wyndham Garden', 'Hawthorn Suites', 'Wingate By Wyndham', 'Ramada', 'Wyndham', 'Wyndham Grand']}
]
