export default {
  quotes: [
    'When you want to succeed as bad as you want to breathe, then you’ll be successful.- Eric Thomas',
    'Hard work beats talent when talent doesn’t work hard.- Tim Notke',
    'A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.- Vince Lombardi',
    'Every great story on the planet happened when someone decided not to give up, but kept going no matter what.- Spryte Loriano',
    'Don’t stop when you’re tired. STOP when you are DONE.- Unknown',
    'Failure will never overtake me if my determination to succeed is strong enough.- Og Mandino',
    'Success… seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.- Conrad Hilton',
    'Aim for the moon. If you miss, you may hit a star.- W. Clement Stone',
    'Action is the foundational key to all success.- Pablo Picasso',
    'The ones who are crazy enough to think they can change the world, are the ones who do.- Unknown',
    'Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier, wish you were better.- Jim Rohn',
    'The question isn’t who is going to let me; it’s who is going to stop me.- Ayn Rand',
    'It does not matter how slowly you go, so long as you do not stop.- Confucius',
    'Little minds are tamed and subdued by misfortune; but great minds rise above it.- Washington Irving',
    'I find that the harder I work, the more luck I seem to have.- Thomas Jefferson',
    'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.- Mark Twain',
    'You don’t have to be great to start, but you have to start to be great.- Zig Ziglar',
    'Nothing is impossible, the word itself says “I’m possible”!- Audrey Hepburn',
    'Life begins at the end of your comfort zone.- Neale Donald Walsh',
    'The will to win, the desire to succeed, the urge to reach your full potential… these are the keys that will unlock the door to personal excellence.- Confucius',
    'Things work out best for those who make the best of how things work out.- John Wooden',
    'Perfection is not attainable, but if we chase perfection we can catch excellence.- Vince Lombardi',
    'Give me a stock clerk with a goal, and I will give you a man who will make history. Give me a man without a goal, and I will give you a stock clerk.- J.C. Penny',
    'Nothing in the world is more common than unsuccessful people with talent.- Unknown',
    'Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.- Dale Carnegie',
    'Expect problems and eat them for breakfast.- Alfred A. Montapert',
    'Success is walking from failure to failure with no loss of enthusiasm.- Winston Churchill',
    'Opportunities don’t happen, you create them.- Chris Grosser',
    'I do not have superior intelligence or faultless looks. I do not captivate a room or run a mile under six minutes. I only succeeded because I was still working after everyone else went to sleep.- Greg Evans',
    'The greatest pleasure in life is doing what people say you cannot do.- Walter Bagehot',
    'The secret of getting ahead is getting started.- Mark Twain',
    'Remember that not getting what you want is sometimes a wonderful stroke of luck.- Dalai Lama',
    'The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.- Henry Ford',
    'All our dreams can come true if we have the courage to pursue them.- Walt Disney',
    'There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.- Ray Goforth',
    'What’s the point of being alive if you don’t at least try to do something remarkable.- Unknown',
    'Don’t watch the clock; do what it does. Keep going.- Sam Levenson',
    'Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won’t feel insecure around you. We are all meant to shine, as children do.- Marianne Williamson',
    'I have not failed. I’ve just found 10,000 ways that won’t work.- Thomas A. Edison',
    'How does one become a butterfly? You must want to fly so much that you are willing to give up being a caterpillar.- Trina Paulus',
    'Take up one idea. Make that one idea your life—think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.- Swami Vivekananda',
    'I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.- Jimmy Dean',
    'Failure is the opportunity to begin again more intelligently.- Henry Ford',
    'There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.- Michael Phelps',
    'Nothing great will ever be achieved without great men, and men are great only if they are determined to be so.  For glory gives herself only to those who have always dreamed of her.- Charles De Gaulle',
    'You got a dream, you gotta protect it. People can’t do something themselves, they wanna tell you, you can’t do it. If you want something, go get it. Period.- Will Smith',
    'The successful warrior is the average man, with laser-like focus.- Bruce Lee',
    'Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.- Stephen R. Covey',
    'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.- Thomas A. Edison',
    'Too many of us are not living our dreams because we are living our fears.- Les Brown',
    'Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.- Helen Keller',
    'Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.- Wayne Dyer',
    'Nothing great ever came that easy.- Kresley Cole',
    'Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter.- Francis Chan',
    'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.- David Brinkley',
    'The greatest achievement was at first, and for a time, but a dream.- Napoleon Hill',
    'Good things come to people who wait, but better things come to those who go out and get them.- Unknown',
    'Great things come to those who don’t wait.- Unknown',
    'The best way to predict the future is to create it.- Peter Drucker',
    'People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.- Tony Robbins',
    'When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down “happy”. They told me I didn’t understand the assignment, and I told them they didn’t understand life.- John Lennon',
    'Ones best success comes after their greatest disappointments.- Henry Ward Beecher',
    'The fishing is best where the fewest go, and the collective insecurity of the world makes it easy for people to hit home runs while everyone else is aiming for base hits. There is just less competition for bigger goals. If you are insecure, guess what? The rest of the world is, too. Do not overestimate the competition and underestimate yourself. You are better than you think.- Timothy Ferris',
    'It’s not about time, it’s about choices. How are you spending your choices?- Beverly Abamo',
    'You will succeed because most people are lazy.- Unknown',
    'The starting point of all achievement is desire.- Napoleon Hill',
    'If you want to achieve greatness stop asking for permission.- Unknown',
    'I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.- Martha Stewart',
    'There are no great men. Just great challenges which ordinary men, out of necessity, are forced by circumstance to meet.- Admiral William Frederick Halsey Jr.',
    'The only place where success comes before work is in the dictionary.- Vidal Sassoon',
    'Some people develop a wish bone where their back bone should be.- Unknown',
    'All progress takes place outside the comfort zone.- Michael John Bobak',
    'No matter how hard the past is, you can always begin again.- Jack Kornfield',
    'Infuse your life with action. Don’t wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen… yourself, right now, right down here on Earth.- Bradley Whitford',
    'You can never cross the ocean unless you have the courage to lose sight of the shore.- Christopher Columbus',
    'If you are not willing to risk the usual you will have to settle for the ordinary.- Jim Rohn',
    'There are two primary choices in life; to accept conditions as they exist, or to accept the responsibility for changing them.- Dennis Waitely',
    'More often than not, successful entrepreneurs are givers and not takers of positive energy.- Olaf Isachsen',
    'Positive thinking won’t let you do anything, but it will let you do everything better than negative thinking will.- Zig Ziglar',
    'The Way Get Started Is To Quit Talking And Begin Doing.- Walt Disney',
    'The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees The Opportunity In Every Difficulty.- Winston Churchill',
    'Don’t Let Yesterday Take Up Too Much Of Today.- Will Rogers',
    'You Learn More From Failure Than From Success. Don’t Let It Stop You. Failure Builds Character.- Unknown',
    'It’s Not Whether You Get Knocked Down, It’s Whether You Get Up.- Vince Lombardi',
    'If You Are Working On Something That You Really Care About, You Don’t Have To Be Pushed. The Vision Pulls You.- Steve Jobs',
    'People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do.- Rob Siltanen',
    'Failure Will Never Overtake Me If My Determination To Succeed Is Strong Enough.- Og Mandino',
    'Entrepreneurs Are Great At Dealing With Uncertainty And Also Very Good At Minimizing Risk. That’s The Classic Entrepreneur.- Mohnish Pabrai',
    'We May Encounter Many Defeats But We Must Not Be Defeated.- Maya Angelou',
    'Knowing Is Not Enough; We Must Apply. Wishing Is Not Enough; We Must Do.- Johann Wolfgang Von Goethe',
    'Imagine Your Life Is Perfect In Every Respect; What Would It Look Like?- Brian Tracy',
    'We Generate Fears While We Sit. We Overcome Them By Action.- Dr. Henry Link',
    'Whether You Think You Can Or Think You Can’t, You’re Right.- Henry Ford',
    'Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing.- Helen Keller',
    'The Man Who Has Confidence In Himself Gains The Confidence Of Others.- Hasidic Proverb',
    'The Only Limit To Our Realization Of Tomorrow Will Be Our Doubts Of Today.- Franklin D. Roosevelt',
    'Creativity Is Intelligence Having Fun.- Albert Einstein',
    'What You Lack In Talent Can Be Made Up With Desire, Hustle And Giving 110% All The Time.- Don Zimmer',
    'Do What You Can With All You Have, Wherever You Are.- Theodore Roosevelt',
    'Develop An ‘Attitude Of Gratitude’. Say Thank You To Everyone You Meet For Everything They Do For You.- Brian Tracy',
    'You Are Never Too Old To Set Another Goal Or To Dream A New Dream.- C.S. Lewis',
    'To See What Is Right And Not Do It Is A Lack Of Courage.- Confucious',
    'Reading Is To The Mind, As Exercise Is To The Body.- Brian Tracy',
    'Fake It Until You Make It! Act As If You Had All The Confidence You Require Until It Becomes Your Reality.- Brian Tracy',
    'The Future Belongs To The Competent. Get Good, Get Better, Be The Best!- Brian Tracy',
    'Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.- Arnold Schwarzenegger',
    'The world breaks everyone, and afterward, some are strong at the broken places.- Ernest Hemingway',
    'All the adversity I’ve had in my life, all my troubles and obstacles, have strengthened me.... You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you.- Walt Disney',
    'There are two ways of exerting one’s strength: one is pushing down, the other is pulling up.- Booker T. Washington',
    'A truly strong person does not need the approval of others any more than a lion needs the approval of sheep.- Vernon Howard',
    'I like criticism. It makes you strong.- LeBron James',
    'There are better starters than me but I’m a strong finisher.- Usain Bolt',
    'He who believes is strong; he who doubts is weak. Strong convictions precede great actions.- Louisa May Alcott',
    'Strength and growth come only through continuous effort and struggle.- Napoleon Hill',
    'Make up your mind that no matter what comes your way, no matter how difficult, no matter how unfair, you will do more than simply survive. You will thrive in spite of it.- Joel Osteen',
    'Tough times never last, but tough people do.- Robert H. Schuller',
    'Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.- William Ellery Channing',
    'Nothing is more beautiful than the smile that has struggled through the tears.- Demi Lovato',
    'I believe in being strong when everything seems to be going wrong. I believe that happy girls are the prettiest girls. I believe that tomorrow is another day and I believe in miracles.- Audrey Hepburn',
    'That which does not kill us makes us stronger.- Friedrich Nietzsche',
    'Sometimes you don’t realize your own strength until you come face to face with your greatest weakness.- Susan Gale',
    'Be very strong... be very methodical in your life if you want to be a champion.- Alberto Juantorena',
    'Life is very interesting. In the end, some of your greatest pains become your greatest strengths.- Drew Barrymore',
    'I like feeling strong. It keeps my mental floor higher.- Pink',
    'I love the man that can smile in trouble, that can gather strength from distress, and grow brave by reflection. ’Tis the business of little minds to shrink, but he whose heart is firm, and whose conscience approves his conduct, will pursue his principles unto death. —Thomas Paine',
    'Stay strong. Stand up. Have a voice.- Shawn Johnson'
  ],
  random () {
    const r = Math.floor(Math.random() * this.quotes.length)
    return this.quotes[r]
  }
}
